### ISSUE TITLE
(JSON) Wrong format when `Export contents as array` checked

### ISSUE THREAD

**Issue by zachguo** [Synthoid/ExportSheetData#3] opened 2016-08-15 00:37 UTC
It should be square brackets instead of curly brackets.

<img width="630" alt="screen shot 2016-08-14 at 5 19 28 pm" src="https://cloud.githubusercontent.com/assets/3478203/17653170/b0e11c1c-6245-11e6-99a5-d8cdd4b966b3.png">

**Comment by Synthoid** [comment] 2016-08-16 02:18
It looks like you have "Export contents as array" checked. This is the expected behavior for that option, as it exports the whole sheet as a raw JSON array (notice the wrapping square brackets). What you may want to try instead is the "Export sheet arrays" option which exports each sheet's contents as a JSON array. We probably should move the "Export contents as array" option in a separate, "Advanced Options" section to prevent any confusion.

**Comment by zachguo** [comment] 2016-08-16 02:32
Thanks for your reply! But, that's illegal JSON format, curly brackets should be replaced by square brackets.

**Comment by Synthoid** [comment] 2016-08-16 03:03
The "Export contents as array" option was created for very specific purposes. This is why the description for it includes "(WARNING: This means the exported data will not be formatted as a stand-alone JSON object.)" "Export sheet arrays" creates a properly formatted JSON blob with each sheet acting as a separate array in the wrapping JSON object, while "Export contents as array" creates a raw JSON Array with each sheet acting as a separate element of the array.

See the attached image for comparisons:

![jsonarrays](https://cloud.githubusercontent.com/assets/6645950/17686576/baf21732-633b-11e6-9789-e6685b893392.png)

**Comment by zachguo** [comment] 2016-08-16 03:45
So there's no way to export a sheet as a 2D array?

**Comment by Synthoid** [comment] 2016-08-16 22:01
Using both "Export contents as array" and "Export sheet arrays" will create a 2D array, albeit a raw JSON array. If a 2D array is all you need that should work, but be aware that it will not be a standalone JSON object.

**Comment by zachguo** [comment] 2016-08-17 01:44
Sorry for the confusion! That's not the 2D array I mean. I mean we can generate a 2D array for each sheet like
```
[
  ["header1", "header2"],
  ["row1_col1_value", "row1_col2_value"],
  ["row2_col1_value", "row2_col2_value"],
]
```
I think this kinda matrix representation is quite useful and common for tabular data.

If we also enable `Export sheet arrays`, a 3D array should be generated.

**Comment by Synthoid** [comment] 2016-08-19 01:15
Ah, I see what you mean now. I think this may be a good fit for an "advanced options" item. [For now, I've created a new issue for 2D array support](https://github.com/Synthoid/ExportSheetData/issues/6). I'll close this issue, since it is technically not an actual problem.

**Closed by Synthoid** 2016-08-19 01:15 UTC
