### ISSUE TITLE
(XML) Allow to not insert tag related to the sheet in multiple sheet export

### ISSUE THREAD

**Issue by grossima** [Synthoid/ExportSheetData#26] opened 2017-04-01 11:25 UTC
Should be very useful have the possibility to chose to hide the "sheet tag" in the multi sheet export, like in this example....
```
<?xml version="1.0" encoding="UTF-8"?>
<data>
  <sheet1>
    <sheet1-row attribute1.1="content 1.1.1" ... attribute1.M="content 1.M.1"/>
    <sheet1-row attribute1.1="content 1.1.2" ... attribute1.M="content 1.M.2"/>
    <sheet1-row attribute1.1="content 1.1.3" ... attribute1.M="content 1.M.3"/>
  </sheet1>
  <sheet2>
    <sheet2-row attribute2.1="content 1.2.1" ... attribute2.N="content 2.N.1"/>
    <sheet2-row attribute2.1="content 1.2.2" ... attribute2.N="content 2.N.2"/>
    <sheet2-row attribute2.1="content 1.2.3" ... attribute2.N="content 2.N.3"/>
  </sheet2>
<!-- .... -->
<sheetZ>
    <sheetZ-row attributeZ.1="content Z.2.1" ... attributeZ.T="content Z.T.1"/>
    <sheetZ-row attributeZ.1="content Z.2.2" ... attributeZ.T="content Z.T.2"/>
    <sheetZ-row attributeZ.1="content Z.2.3" ... attributeZ.T="content Z.T.3"/>
  </sheetZ>
</data>
```

Hiding   <sheet1>,  <sheet2>, ... , <sheetZ> tags...
```
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <sheet1-row attribute1.1="content 1.1.1" ... attribute1.M="content 1.M.1"/>
    <sheet1-row attribute1.1="content 1.1.2" ... attribute1.M="content 1.M.2"/>
    <sheet1-row attribute1.1="content 1.1.3" ... attribute1.M="content 1.M.3"/>
    <sheet2-row attribute2.1="content 1.2.1" ... attribute2.N="content 2.N.1"/>
    <sheet2-row attribute2.1="content 1.2.2" ... attribute2.N="content 2.N.2"/>
    <sheet2-row attribute2.1="content 1.2.3" ... attribute2.N="content 2.N.3"/>
<!-- .... -->
    <sheetZ-row attributeZ.1="content Z.2.1" ... attributeZ.T="content Z.T.1"/>
    <sheetZ-row attributeZ.1="content Z.2.2" ... attributeZ.T="content Z.T.2"/>
    <sheetZ-row attributeZ.1="content Z.2.3" ... attributeZ.T="content Z.T.3"/>
</data>
```
There are some import tools that process the row of different entity type, as a simple list of "one level tag", as in the second example.

Another option should be create the sheetN-row tag name (<sheet1-row>, <sheet2-row>, ...), not with the first column of the table, but with the name of the sheet.

Thanks for the wonderful effort on this project.

**Comment by Synthoid** [comment] 2017-04-09 17:33
This is one of those things that just seems obvious after someone says it. Thanks!

I've broken this issue down into two distinct issues: [Unwrapping sheets](https://github.com/Synthoid/ExportSheetData/issues/28) and [Sequential complex elements](https://github.com/Synthoid/ExportSheetData/issues/29). Mostly because half of the issue is sharing functionality with JSON and the other half is exclusively XML. This should group any new ideas being posted to the relevant ticket, so I'm going to close this issue and move the discussion into the more specific tickets.

**Closed by Synthoid** 2017-04-09 17:33 UTC
