### ISSUE TITLE
3 XML level nested

### ISSUE THREAD

**Issue by jamacoe** [Synthoid/ExportSheetData#36] opened 2017-09-18 13:21 UTC
How do I have to design the sheet and what settings do I have to choose in the sidebar, in order to get a 3 level nested xml output, like:

```
<root>
 <fruit>
  <description>
   <en>Some text</en>
   <de>etwas text</de>
   <es>poco texto</es>
  </description>
 </fruit>
</root>
```
I only seem to achive this if I include the last level as text in the field content, using a sheet like:

```
root   description          description           description  
fruit  <en>Some text</en>   <de>etwas text</de>   <es>poco texto</es>
```

**Comment by Synthoid** [comment] 2017-09-18 14:01
This has to do with [Complex Nested Elements.](https://github.com/Synthoid/ExportSheetData/issues/19) I am currently working to support this feature, and it should be ready soon!

For now, I am closing this issue since it is a duplicate of Complex Nested Elements.

**Closed by Synthoid** 2017-09-18 14:01 UTC
