### ISSUE TITLE
Only last line is exported in JSON

### ISSUE THREAD

**Issue by sailgrib** [Synthoid/ExportSheetData#49] opened 2017-12-31 10:54 UTC
Hi,

When trying to export data in JSON, only the last is actually exported.
I have tried on multiple Google Sheets with the same result.
I have left all the default parameters and I am exporting only the Current sheet.

Henri

**Comment by Synthoid** [comment] 2017-12-31 19:04
You don't have Nested Elements enabled? This issue sounds like an output using nested elements without using proper key syntax.

Would you be able to link to an example sheet?

**Comment by Synthoid** [comment] 2018-02-05 03:48
Closing this issue as it seems to be the expected behavior when Nested Elements is enabled with incorrect key formatting.

**Closed by Synthoid** 2018-02-05 03:48 UTC
